core/bookings/api/urls.py
from django.urls import path
from . import views
from rest_framework import routers

app_name = 'bookings_api'
router = routers.SimpleRouter()
router.register('trips', views.TripViewSet, basename='Trip')

urlpatterns = []

urlpatterns += router.urls

core/bookings/urls.py
from django.urls import path
from . import views

app_name = 'bookings'

urlpatterns = [
    path('', views.TripListView.as_view(), name='list_trip'),
    path('new/', views.TripCreateView.as_view(), name='create_trip'),
    path('<int:pk>/edit/', views.TripUpdateView.as_view(), name='update_trip'),
    path('<int:pk>/delete/', views.TripDeleteView.as_view(), name='delete_trip'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trips/', include('bookings.urls', namespace='bookings')),
    path('trips/', include('bookings.urls', namespace='bookings')),
    path('api/', include('bookings.api.urls', namespace='bookings_api')),
]

core/bookings/models.py
from django.db import models
from django.core.validators import MinValueValidator


class Trip(models.Model):
    destination = models.CharField(max_length=100)
    departure_date = models.DateField()
    return_date = models.DateField()
    number_of_travelers = models.IntegerField(default=1, validators=[MinValueValidator(1)])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return f'{self.destination}: ({self.departure_date} - {self.return_date})'

core/bookings/forms.py
from django import forms
from .models import Trip
from django.utils import timezone
from django.core.exceptions import ValidationError


class TripForm(forms.ModelForm):
    class Meta:
        model = Trip
        fields = '__all__'
        widgets = {
            'destination': forms.TextInput(attrs={'class': 'form-control'}),
            'departure_date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'return_date':forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'number_of_travelers': forms.NumberInput(attrs={'class': 'form-control'}),
        }

    def clean(self):
        cd = self.cleaned_data
        if cd['departure_date'] < timezone.now().date() or cd['return_date'] < cd['departure_date']:
            raise ValidationError('Enter a valid date!')
        return super().clean()

core/bookings/api/views.py
from rest_framework.response import Response
from rest_framework import viewsets
from rest_framework.permissions import AllowAny
from rest_framework import status
from django.shortcuts import get_object_or_404
from bookings.models import Trip
from .serializers import TripSerializer


class TripViewSet(viewsets.ViewSet):
    permission_classes = [AllowAny]
    serializer_class = TripSerializer

    def list(self, request):
        qs = Trip.objects.all()
        ser_data = self.serializer_class(instance=qs, many=True)
        return Response(ser_data.data, status=status.HTTP_200_OK)

    def create(self, request):
        ser_data = self.serializer_class(data=request.POST)
        if ser_data.is_valid():
            ser_data.save()
            return Response(ser_data.data, status=status.HTTP_201_CREATED)

    def update(self, request, pk=None):
        trip = get_object_or_404(Trip, pk=pk)
        ser_data = self.serializer_class(instance=trip, data=request.POST)
        if ser_data.is_valid():
            ser_data.save()
            return Response(ser_data.data, status=status.HTTP_201_CREATED)
        return Response(ser_data.errors, status=status.HTTP_400_BAD_REQUEST)

    def partial_update(self, request, pk=None):
        trip = get_object_or_404(Trip, pk=pk)
        ser_data = self.serializer_class(instance=trip, data=request.POST, partial=True)
        if ser_data.is_valid():
            ser_data.save()
            return Response(ser_data.data, status=status.HTTP_201_CREATED)
        return Response(ser_data.errors, status=status.HTTP_400_BAD_REQUEST)

    def destroy(self, request, pk=None):
        trip = get_object_or_404(Trip, pk=pk)
        trip.delete()
        return Response({'message': 'Trip deleted'}, status=status.HTTP_204_NO_CONTENT)

core/bookings/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .models import Trip
from .forms import TripForm
from django.contrib import messages
from django.views.generic import DeleteView


class TripListView(View):
    template_name = 'bookings/list_trips.html'

    def get(self, request):
        trips = Trip.objects.all()
        return render(request, self.template_name, {'trips': trips})


class TripCreateView(View):
    template_name = 'bookings/create_trip.html'
    form_class = TripForm

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            Trip.objects.create(
                destination=cd['destination'],
                departure_date=cd['departure_date'],
                return_date=cd['return_date'],
                number_of_travelers=cd['number_of_travelers'],
            )
            messages.success(request, 'Your trip has been successfully booked.', 'success')
            return redirect('bookings:list_trip')
        return render(request, self.template_name, {'form': form})


class TripUpdateView(View):
    form_class = TripForm
    template_name = 'bookings/update_trip.html'

    def setup(self, request, *args, **kwargs):
        self.trip_instance = get_object_or_404(Trip, id=kwargs['pk'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        trip = self.trip_instance
        form = self.form_class(instance=trip)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        trip = self.trip_instance
        form = self.form_class(request.POST, instance=trip)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your trip has been successfully edited', 'success')
            return redirect('bookings:list_trip')
        return render(request, self.template_name, {'form': form})


class TripDeleteView(View):
    template_name = 'bookings/confirm_delete.html'

    def setup(self, request, *args, **kwargs):
        self.trip_instance = get_object_or_404(Trip, id=kwargs['pk'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        trip = self.trip_instance
        return render(request, self.template_name, {'trip': trip})

    def post(self, request, *args, **kwargs):
        trip = self.trip_instance
        trip.delete()
        messages.success(request, 'Your trip has been successfully deleted', 'success')
        return redirect('bookings:list_trip')

core/bookings/templates/bookings/confirm_delete.html
{% extends 'base.html' %}

{% block title %} Delete Trip {% endblock %}

{% block content %}
<p>Are you sure you want to delete this trip?  <strong>{{ trip }}</strong>
  </p>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
    </form>

{% endblock %}

core/bookings/templates/bookings/create_trip.html
{% extends 'base.html' %}

{% block title %} Create Trip {% endblock %}

{% block content %}

<form action="" method="post" class="col-md-3">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" class="btn btn-primary" value="Add">
</form>

{% endblock %}

core/bookings/templates/bookings/list_trips.html
{% extends 'base.html' %}

{% block title %} Trips List {% endblock %}

{% block content %}

<table class="table">
  <thead>
    <tr>
      <th scope="col">R</th>
      <th scope="col">Destination</th>
      <th scope="col">Departure Date</th>
      <th scope="col">Return Date</th>
      <th scope="col">Number of Travelers</th>
      <th scope="col">Edit</th>
      <th scope="col">Remove</th>
    </tr>
  </thead>
  <tbody>
  {% for trip in trips%}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ trip.destination }}</td>
      <td>{{ trip.departure_date }}</td>
      <td>{{ trip.return_date }}</td>
      <td>{{ trip.number_of_travelers }}</td>
      <td><a href="{% url 'bookings:update_trip' trip.id %}" class="btn btn-secondary">Edit</a></td>
      <td><a href="{% url 'bookings:delete_trip' trip.id %}" class="btn btn-danger">Remove</a></td>
    </tr>
    <tr>
  {% endfor %}
</table>
<p><a href="{% url 'bookings:create_trip' %}" class="btn btn-primary">Add Trip</a></p>

{% endblock %}

core/bookings/templates/bookings/update_trip.html
{% extends 'base.html' %}

{% block title %} Edit Trip {% endblock %}

{% block content %}

<form action="" method="post" class="col-md-3">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" class="btn btn-primary" value="Edit">
</form>

{% endblock %}

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <style>
        .layout{
            padding: 20px;
            margin-bottom: 20px;
            background-color: whitesmoke;
        }
    </style>
    {% block extra_headers %} {% endblock %}

</head>
<body>
    {% include 'inc/navbar.html' %}
    <div class="layout">
        {% include 'inc/messages.html' %}
        {% block content %} {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

core/templates/inc/messages.html
{% if messages %}
  {% for msg in messages %}
    <p class="alert alert-{{msg.tags}} col-md-6">{{msg}}</p>
  {% endfor %}
{% endif %}

core/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="{% url 'bookings:list_trip' %}">Trips</a>
      </div>
  </div>
</nav>